name: Check requirements.txt git URLs are properly formatted

on: pull_request

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: sed -i '/git\+/ { /\.git$/! s/$/.git/ }' requirements.txt
      - uses: getsentry/action-git-diff-suggestions@main
        with:
          message: To keep the `requirements.txt` consistent, please update the following dependencies.
